### ISSUE TITLE
Timelines are not loading

### ISSUE THREAD

**Issue by SurendraRedd** [innerdoc/nlp-history-timeline#1]
Hello,

I have installed the streamlit timeline for testing after cloing the repository and running the file, It is always displaying as loading.
Can you please let me know the problem why it is loading like that.

https://cdn.knightlab.com/libs/timeline3/latest - cdn path is not working/available
https://www.innerdoc.com/nlp-timeline-demo/ - in this link also timelines are not getting loaded.

**Comment by innerdoc** [comment]
Hi @SurendraRedd , the CDN was not working yesterday. Fortunately, it is available now. This is an external dependecy and is maintained by knightlab.com . 

Hope you enjoy the timeline now!

**Comment by SurendraRedd** [comment]
Thanks for the update. Yes its working now. 
Very Useful package.
